POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Juan 2",
    "number": "25656"

}

###

POST https://fullstackopen-backend-oybc.onrender.com/api/persons
Content-Type: application/json

{
    "name": "Juan Perez",
    "number": "25656"

}